### PR TITLE
Format Currency Extension

### PR DESCRIPTION
**Pull request by priyanshi1282**
### Screenshots : 
dmeo2
INRdemo

### CODE REVIEW

**Comment by whiteHatpro** [comment]
@priyanshi1282 nice work!!

**Comment by priyanshi1282** [comment]
Thanks  @whiteHatpro  fir the compliment 😄

**Comment by harshita214** [comment]
@priyanshi1282 you have added the extension twice revert it, also the image is not loading properly in the readme file 
Kindly do the required changes suggested

**Comment by harshita214** [comment]
@priyanshi1282 ??

**Comment by priyanshi1282** [comment]
@harshita214  sorry for the delay, I'll b updating it today itself

**Comment by harshita214** [comment]
@priyanshi1282 I have put labels on #206 instead of this

**Pull request merged**
