### PR TITLE
social access added in Tab Tracker extension

### PR DESCRIPTION
**Pull request by shashank2906**
### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [ ] New Extension
- [x] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

UI Preview

### CODE REVIEW

**Comment by shashank2906** [comment]
can someone review and merge this pr .

**Comment by harshita214** [comment]
Sure 👍

**Comment by shashank2906** [comment]
@harshita214  hello mam , kindly review and merge the pr .

**Comment by harshita214** [comment]
@shashank2906 Can you tell the issue number under which you solved this issue

**Comment by shashank2906** [comment]
issue no #129

**Comment by harshita214** [comment]
@shashank2906 the code looks good to me 👍 
Kindly add the video in readme file

**Comment by shashank2906** [comment]
video file added in ui preview

**Comment by shashank2906** [comment]
@harshita214  video file added in ui preview

**Comment by shashank2906** [comment]
@harshita214  video added in readme file

**Comment by shashank2906** [comment]
@harshita214 video added in readme file .

**Comment by shashank2906** [comment]
@whiteHatpro kindly review and merge the PR .

**Comment by whiteHatpro** [comment]
@shashank2906 good work!!
Thanks for contributing🚀🚀💛

**Pull request merged**
