### PR TITLE
Added Web IDE - Github

### LINKED ISSUE #274: GitHub Web IDE
### Is your extension request related to a problem? Please describe.

This extension adds to any GitHub repository a new drop down menu which offers links to a number of online services that allow viewing the source code of the repository in an IDE like interface.

### Describe the solution you'd like.

A implementation in the form of Chrome Extension

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the extension here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #274 

### 👨‍💻 Changes proposed
- Extension adds a lot of integrations and options available to a github Repository
- For example, Github Dev, VSCode, GitLab, etc.

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

image

### If clicked, Sandbox
image

### If Clicked, VSCode Dev
image

@harshita214 Review this PR. 
Thank you !

### CODE REVIEW

**Comment by hariketsheth** [comment]
Since this add utility, I request you to give Level 3 label for this PR.

**Comment by harshita214** [comment]
This looks so great 
just one thing, add extension video also in readme file

You can view other extension for idea on how to make video , for example [this](https://github.com/harshita214/Chrome-Extension/tree/main/Dark%20ColorGen)

**Comment by hariketsheth** [comment]
> This looks so great just one thing, add extension video also in readme file
> 
> You can view other extension for idea on how to make video , for example [this](https://github.com/harshita214/Chrome-Extension/tree/main/Dark%20ColorGen)

@harshita214 Proceed 👍🏻

**Comment by harshita214** [comment]
Amazing work and Idea, I am surely going to use this
Merging the PR 🚀 
Thanks for contributing 💙

**Pull request merged**
