### PR TITLE
Pomodoro Extension Added

### PR DESCRIPTION
**Pull request by shreya024**
I have added the Pomodoro Extension
Related Issue: #170

### CODE REVIEW

**Comment by whiteHatpro** [comment]
@shreya024 please add the ss and video of the extension

**Comment by shreya024** [comment]
> @shreya024 please add the ss and video of the extension

## Screenshots


## Simulation Video
pomodoro

**Comment by shreya024** [comment]
> @shreya024 please add the ss and video of the extension

Added @whiteHatpro

**Comment by shreya024** [comment]
@harshita214 Kindly add the labels

**Pull request merged**
