### PR TITLE
Added HackPrank

### LINKED ISSUE #263: Fake Hacks
Can I add this project which removes all the images and replace it with hacked images like it can be used for fake hacking.It is simply
 built using javascript Can I add this?

### PR DESCRIPTION
**Pull request by SamarthKadam**
### 🔧 Check List (Check the type of issue it fixes) 

- [ x] New Extension 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by harshita214 — CHANGES_REQUESTED** [review]
Kindly add a extension video

You can view other extension for idea on how to make video , for example [this](https://github.com/harshita214/Chrome-Extension/tree/main/Dark%20ColorGen)

Also have you used any api?

**Comment by SamarthKadam** [comment]
@harshita214  No Api used.  So below is the video

https://user-images.githubusercontent.com/87573175/171045135-6ca8730f-6a51-469f-8799-3120d9ab1ba6.mp4

**Comment by harshita214** [comment]
@SamarthKadam kindly add readme file and in that add ss and video of extension

**Comment by SamarthKadam** [comment]
Now this would be not accounted for GSSoc .

**Pull request closed without merging**
