### PR TITLE
issue #57 wordle extension made

### PR DESCRIPTION
**Pull request by ronitblenz**
I have made a Chrome extension which can detect possible answers for Wordle Game
Link to the game - https://www.nytimes.com/games/wordle/index.html

Thanks

### CODE REVIEW

**Comment by harshita214** [comment]
@ronitblenz kindly add a video of implementation of extension , and also add it in readme file

**Comment by ronitblenz** [comment]
https://user-images.githubusercontent.com/91361382/153817974-b9bdd3d1-40fe-40ae-8aca-beac55428c95.mp4

**Comment by ronitblenz** [comment]
Here is the demo

**Comment by ronitblenz** [comment]
Plz check my PR and merge it

**Comment by harshita214** [comment]
Is this your demo video?

**Comment by ronitblenz** [comment]
No, Basically Its the inspiration of my extension, its similar to this, I am having tough time in recording my screen..thats why

**Comment by harshita214** [comment]
No that's not allowed. kindly Record by phone in that case  , but showing the video which is not yours is not allowed

**Comment by harshita214** [comment]
@ronitblenz Update?

**Pull request closed without merging**
