### PR TITLE
Added COVID-19 Live Statistics Chrome Extension

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
# PR Description

• Adds a Chrome extension to retrieve and display live COVID-19 Statistics

### CODE REVIEW

**Comment by harshita214** [comment]
Kindly first make an Issue before creating a PR describing the extension and its features

**Comment by abhilipsasahoo03** [comment]
> Kindly first make an Issue before creating a PR describing the extension and its features

Closes [#104](https://github.com/harshita214/Chrome-Extension/issues/104)

**Comment by abhilipsasahoo03** [comment]
> Kindly first make an Issue before creating a PR describing the extension and its features

Also, is this repo open to only JWOC participants or does it welcome contributions from everyone, because I'm not a JWOC participant and I'm interested in contributing to this repo. Sorry, should've asked this question in the beginning.

**Comment by harshita214** [comment]
> Also, is this repo open to only JWOC participants or does it welcome contributions from everyone? Because I'm not a JWOC participant and I'm interested in contributing to this repo. Sorry, should've asked this question in the beginning.

This repo is open for all, and all can contribute to this repository and are welcomed. For the participants, there are some points and levels which are assigned but otherwise, all contributions are welcomed. I am glad to know you are interested in repo please feel free to contribute to repo 💙 

Thanks for contribution 👍 
Merging the PR 🚀

**Pull request merged**
