### PR TITLE
added word of the day extension 

### PR DESCRIPTION
**Pull request by mnnkhndlwl**
whenever user clicks on this extension it gives a random word and its meaning
image

https://user-images.githubusercontent.com/75252077/152735363-9d5d21eb-bfff-4fc4-96f4-7ee9bfe7c9e2.mp4

### CODE REVIEW

**Comment by harshita214** [comment]
Hey @mnnkhndlwl good job, can you increase the width of the extension. Also, add a background and a button which when clicked will generate a random word & meaning

**Comment by mnnkhndlwl** [comment]
@harshita214 done 

https://user-images.githubusercontent.com/75252077/152746087-2dc44abe-ec3c-4277-8c09-12ab6506463a.mp4

**Comment by harshita214** [comment]
Awesome work @mnnkhndlwl 👏 
merging the PR 🚀 
Thanks for contributing 💛

**Comment by mnnkhndlwl** [comment]
@harshita214  can you add JWOC and medium labels in it because our scores will be counted by the labels in pull requests

**Comment by mnnkhndlwl** [comment]
image

**Comment by harshita214** [comment]
Done! Sorry for confusion

**Pull request merged**
