### PR TITLE
frontend changes added

### PR DESCRIPTION
**Pull request by shashank2906**
Added all the frontend and design changes in the Tab Tracker directory .
Functionality yet to be added .

### CODE REVIEW

**Comment by whiteHatpro** [comment]
> Added all the frontend and design changes in the Tab Tracker directory . Functionality yet to be added .

did u added all the functionalities

**Comment by harshita214** [comment]
> > Added all the frontend and design changes in the Tab Tracker directory . Functionality yet to be added .
> 
> did u added all the functionalities

@shashank2906 ??

**Comment by shashank2906** [comment]
Actually all the frontend functionalities are complete .
I am working on the DOM to complete other functionalities .
It would be very helpful for me if you merge this current PR with all the frontend changes .

**Comment by whiteHatpro** [comment]
> Actually all the frontend functionalities are complete . I am working on the DOM to complete other functionalities . It would be very helpful for me if you merge this current PR with all the frontend changes .

@shashank2906 please complete the extension with the screenshots and video and they we'll review the pr!!

**Comment by shashank2906** [comment]
okk sure , I need a little time

**Comment by harshita214** [comment]
@shashank2906 ?

**Comment by shashank2906** [comment]
i need some help in the extention , I have added some bootstrap in the head tag but chrome is not accepting bootstrap or other libraries , i wanted some help in finding out a way to do this .

**Pull request closed without merging**
