### PR TITLE
 Worked on issue #199 SayIt

### LINKED ISSUE #199: Say It 🔊
Hello @harshita214 👋🏻 , as a GSSOC'22 Contributor  i would like to give my contribution to this repo by adding the `Say It 🔊` 

<h1 align="center">Say It 🔊</h1>

 ### What this Extension Do ??
> These Extension help the user to convert the Entered `Text To Speech` which will help to learn how to pronounce that entered text . Sounds cool 😎right

 ### Tech Stack  📚
>  HTML 🏷
>  CSS 🎨
>  JS 🎁

` Note  :    If you like my idea , pls assign these issue to me and comment down below so that i can start working on this COOL Extension . `

### PR DESCRIPTION
**Pull request by RiyaBhandari-2811**
<h1 align="center">Say It 🔊</h1>

## Description 📜

- These Extension help the user to convert the Entered `Text To Speech` which will help to learn how to pronounce that entered text . Sounds cool 😎right

Fixes #199 

<hr />

## Type of change 📝

- New feature (non-breaking change which adds functionality)

<hr />

## Domain of Contribution 📊

- [x] HTML
- [x]  CSS
- [x] JS

<hr />
 
## Checklist ✅

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added required screenshot/gif depicting the working of the project in the folder
- [x] I am a GSSoC'22 contributor

<hr />

## Screenshots / Gif 📸

SayItSS

https://user-images.githubusercontent.com/85748264/159112155-223c0ae3-d3df-498c-8ae7-d09710ab9573.mp4

### CODE REVIEW

**Comment by harshita214** [comment]
Awesome 👏 
Kindly add a picture of the extension also in readme file
Rest is good!

**Comment by RiyaBhandari-2811** [comment]
> Awesome 👏 Kindly add a picture of the extension also in readme file Rest is good!

@harshita214  I've Added the picture in readme file , kindly pls check it whether you can view it or not at your end .

**Comment by RiyaBhandari-2811** [comment]
@harshita214 ??

**Comment by harshita214** [comment]
Awesome ✨ 
Merging the PR 🚀 
Thanks for contributing 💛

**Pull request merged**
