### PR TITLE
Minor Enhancement in Documentation

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
## PR Description

Made improvements in README such as:
- Updated contents in the Extension Table
- Replaced low resolution images with high quality ones and added new extension example image. 
- Added Code of Conduct file and a corresponding section linking to that in README as well
- Slight styling changes

## Issue linked

Closes issue (#220 )

## Screenshots
Screenshot_2022-04-04-23-52-34-902_com android chrome
Screenshot_2022-04-04-23-52-40-681_com android chrome
Screenshot_2022-04-04-23-52-47-226_com android chrome
Screenshot_2022-04-04-23-52-54-969_com android chrome
Screenshot_2022-04-04-23-52-59-018_com android chrome

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
Also, @harshita214 when you review my PR please let me know if there's any chance you could increase my PR level. Don't you think it should be more than Level0?

**Comment by abhilipsasahoo03** [comment]
> Sure 👍 

Also, let me know if any change is required

**Comment by harshita214** [comment]
@abhilipsasahoo03 Good Work!
Merging the PR 🚀 
Thanks for Contributing 💛

**Comment by harshita214** [comment]
Also assigned you level1 🎊

**Comment by abhilipsasahoo03** [comment]
> Also assigned you level1 🎊 

Thank you so much! :)

**Pull request merged**
