### PR TITLE
created solution of #113 issue

### PR DESCRIPTION
**Pull request by MeetaHaldar**
created programming meme extension.

### CODE REVIEW

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes
- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

Kindly complete 2nd and 3rd point

**Comment by MeetaHaldar** [comment]
but i already make a PR 
should  i change it ??
i can add a readme  file
but i don't know how to add tags  
please help me @harshita214

**Comment by harshita214** [comment]
@MeetaHaldar you have to add a readme file describing your extension and then add ss , video of extension implementation

**Comment by harshita214** [comment]
@MeetaHaldar ?

**Comment by harshita214** [comment]
@MeetaHaldar kindly do the changes

**Comment by MeetaHaldar** [comment]
sorry for the delay but there is another repo name "awesome chrome extension" i had made a PR on that repo about this same issue . and that PA told me to not contribute same thing to both places . if you are agree to make a PR on this repo too then i can do PR i have already made that chrome extension. @harshita214

**Comment by harshita214** [comment]
Yes that's correct, in that case I am closing this issue. Kindly contribute to different issue

**Pull request closed without merging**
