### PR TITLE
Fix #149 UI weather extension

### LINKED ISSUE #149: ui enhancement of weather extension
can i work on improving weather extension ui

### PR DESCRIPTION
**Pull request by harshit0571**
put all the background pics in the folder

### CODE REVIEW

**Comment by harshita214** [comment]
> @harshit0571 kindly add the ss and video of the enhancement!!

@harshit0571 ^

**Comment by harshit0571** [comment]
newdisplay1
newdisplay2
newdisplay3

**Comment by harshita214** [comment]
@harshit0571 good work
But you have not added a video implementation kindly do that also

**Comment by harshit0571** [comment]
Ok I will add the video today

**Comment by harshit0571** [comment]
https://user-images.githubusercontent.com/62325935/159894770-d7a9acb3-5d10-4597-9813-051dbfd6a59c.mp4

**Comment by harshit0571** [comment]
Added the vid

**Comment by harshita214** [comment]
@harshit0571 what we meant was to add it in readme
Rest all is good 👍

**Comment by Spring-dot** [comment]
@harshit0571 ??

**Pull request closed without merging**
