### PR TITLE
Changed the HTML and CSS codes to make an attractive UI for Quotes Extension.

### PR DESCRIPTION
**Pull request by AKD-01**
In the Quotes Extension, I modified the few lines of HTML code (popup.html) and CSS code (style.css) for designing an eye-catching and attractive UI. Also had made some changes in the readme.md of the quotes extension.

### CODE REVIEW

**Comment by whiteHatpro** [comment]
@AKD-01 add the ss of the enhancements

**Comment by AKD-01** [comment]
@whiteHatpro The screenshots are attached below: 
Quotes_1
Quotes_2
Quotes_3
Quotes_4
IMAGE 1 & 2 : The earlier UI.
IMAGE 3 & 4 : The UI which I created.

**Comment by AKD-01** [comment]
@whiteHatpro 
Thanks for the appreciation! :)
Could you please add GSSOC label to this pr.

**Comment by harshita214** [comment]
@AKD-01 kindly update the readme file also by adding the current SS of the extension

**Comment by AKD-01** [comment]
@harshita214 I have updated the readme.md and had added the new screenshots too. Have sent you the pr regarding the same, you can check and merge. :)

**Comment by harshita214** [comment]
@AKD-01 Done and merged the PR 🚀

**Pull request merged**
