### PR TITLE
added news extension

### PR DESCRIPTION
**Pull request by Mrjoy832**
Hey! @harshita214 , I am **TRIDIB BAG**, GSSOC'22 contributor, Created issue  #131 
Now I have raised PR regarding the same, which will help to picks up top viral news of all over the world.
Please check my PR.

# My Extension looks like :

image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
> @Mrjoy832 looks fine
> can you add the video of the extension!! 

Ok I will add

**Comment by harshita214** [comment]
@Mrjoy832 ?

**Comment by Mrjoy832** [comment]
> @Mrjoy832 ?

Will be done by today...I had my midterm exam so I was little busy

**Comment by Mrjoy832** [comment]
Hey! @harshita214 , I have added the video please check and merge

**Comment by Mrjoy832** [comment]
> @Mrjoy832 ?

@harshita214 kindly check

**Comment by harshita214** [comment]
@Mrjoy832 I am unable to see your code 
@whiteHatpro Is code visible to you?

**Comment by Mrjoy832** [comment]
> @Mrjoy832 I am unable to see your code 
> @whiteHatpro Is code visible to you?

I will update by morning today wait a little

**Comment by Mrjoy832** [comment]
@harshita214 , @whiteHatpro , Code updated please check

**Comment by harshita214** [comment]
@Mrjoy832 Code is incomplete now
Also, add video implementation

**Comment by Mrjoy832** [comment]
> @Mrjoy832 Code is incomplete now
> Also, add video implementation

Okay

**Comment by whiteHatpro** [comment]
> > @Mrjoy832 Code is incomplete now
> > Also, add video implementation
> 
> Okay

Do it by end of day!!!

**Comment by Mrjoy832** [comment]
> > > @Mrjoy832 Code is incomplete now
> > > Also, add video implementation
> > 
> > 
> > Okay
> 
> Do it by end of day!!!



> 

@whiteHatpro , I have added video showing the upload process in chrome web store , code is complete ...and video is added in readme file

**Comment by harshita214** [comment]
@Mrjoy832 Sure will review it

**Comment by Mrjoy832** [comment]
@harshita214 , please check and merge..it's over a month

**Comment by harshita214** [comment]
Good Work @Mrjoy832 👏 
Merging the PR 🚀 
Thanks for Contributing 💛

**Pull request merged**
