### PR TITLE
Improved ui issue

### PR DESCRIPTION
**Pull request by iamrahulmahato**
issue #123

Description 📜
Improved HTML
Improved CSS
Improved javascript

 I have performed a self-review of my own code or work.
 I have commented my code, particularly in hard-to-understand areas.
 My changes generates no new warnings.
 I'm GSSoC'22 contributor

DEMO11

### CODE REVIEW

**Comment by harshita214** [comment]
@iamrahulmahato Kindly update readme file with SS and video also

**Comment by iamrahulmahato** [comment]
@harshita214 updated

**Comment by harshita214** [comment]
@iamrahulmahato, kindly add ss also. As you have added above

**Comment by iamrahulmahato** [comment]
@harshita214  ss added

**Comment by harshita214** [comment]
Great! Merging the PR 🚀

**Pull request merged**
