### PR TITLE
Added Simple Interest Calculator Extension

### PR DESCRIPTION
**Pull request by Aniket-508**
Solves #41

### CODE REVIEW

**Comment by Aniket-508** [comment]
@harshita214 Please have a look at this.

**Comment by harshita214** [comment]
@Aniket-508 In the readme file picture is not loading, also add an example of extension working.

image

**Comment by Aniket-508** [comment]
@harshita214 Can you check it now?

**Comment by harshita214** [comment]
Yes, I can see now, @Aniket-508 for Time input it should show two options for years and months. Please add that option also

**Comment by harshita214** [comment]
Merged 🚀 
Great @Aniket-508 ✨ 
Thanks for contributing 💛

**Pull request merged**
