### PR TITLE
Added pokemon generator extension

### LINKED ISSUE #273: Add Pokemon generator extension
Extension displays random pokemon and shows its type, attack, defense and speed. Below is the screenshot of the extension I made
Screenshot 2022-05-24 000840

### PR DESCRIPTION
**Pull request by Priyanshi662**
### 🛠️ Fixes Issue
Closes #273 

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by harshita214 — CHANGES_REQUESTED** [review]
Kindly add video of extension in readme file
Rest looks good to me 👍

**Comment by Priyanshi662** [comment]
ok done @harshita214 

https://user-images.githubusercontent.com/77521822/171120958-bdb6975f-f679-4892-8fe3-93766d0854ca.mp4

**Comment by Priyanshi662** [comment]
editing the screenshot too
Capture

**Comment by harshita214** [comment]
Good work @Priyanshi662 
Merging the PR 🚀 
Thanks for contributing 💛

**Pull request merged**
