### PR TITLE
added Breaking bad project

### PR DESCRIPTION
**Pull request by iamrahulmahato**
Issue no #119

Project title
(BreakingBad)

Project Description
(BreakingBad is Chrome extension which generate random quote from famous web series Breaking Bad)

Stack:

Html
CSS
JavaScript
Web API

ScreenShot
demo2

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
Hi @harshita214  kindly review my PR

**Comment by harshita214** [comment]
Sure 👍

**Comment by harshita214** [comment]
Good work @iamrahulmahato 
Just one thing kindly add 2 Screenshots of extension, just like you have added above, rest all is good 👍

**Comment by iamrahulmahato** [comment]
@harshita214 all done added
ss12
ss11

**Comment by iamrahulmahato** [comment]
@harshita214 all done added
ss12
ss11

**Comment by iamrahulmahato** [comment]
@harshita214 all done 
ss12
ss11

**Comment by harshita214** [comment]
Great 🚀 
Merging the PR
Thanks for contributing 💛

**Pull request merged**
