### PR TITLE
Paste anything to generate a QR code for it

### PR DESCRIPTION
**Pull request by adi2002vicky**
Paste anything to generate a QR code for it

### CODE REVIEW

**Comment by harshita214** [comment]
Hey, @adi2002vicky are u contributing to the open-source program? Just asking if in case you are a participant of JWOC or GSSOC then I will be assigning level/marks?

**Comment by adi2002vicky** [comment]
Hii @harshita214  mam/sir I am Gssoc2022 participants

**Comment by harshita214** [comment]
Okay Sure 👍 
Can you add pictures of extension and its working, also add a video implementation

**Comment by adi2002vicky** [comment]
sure mam

**Comment by adi2002vicky** [comment]
Screenshot 2022-03-03 172940
Screenshot 2022-03-03 173204

https://user-images.githubusercontent.com/78430607/156561765-fb310893-c406-4db7-942f-f1dbdccd178c.MP4

mam pls assigned me then merge pr

**Comment by harshita214** [comment]
Can you add this in your readme file, secondly give example video for website QR generator

**Comment by adi2002vicky** [comment]
pls check again mam

**Comment by harshita214** [comment]
@adi2002vicky kindly give an example video for a website QR generator, what I mean is add a website URL in text box and then generate the QR code. Make a video of the above example as suggested and then update the readme file.

**Comment by adi2002vicky** [comment]
https://user-images.githubusercontent.com/78430607/156920084-b627be31-c7ad-4899-bdd0-7b6858cc5582.MP4
done mam check again

**Comment by harshita214** [comment]
Sure, Good Work @adi2002vicky 
Merging the PR ,Thanks for contributing 💛

**Pull request merged**
