### PR TITLE
Currency Convertor Extension Added

### PR DESCRIPTION
**Pull request by Atharv-110**
### Screenshots -
project

### Consider it under GSSoC'22

### CODE REVIEW

**Comment by harshita214** [comment]
@Atharv-110 good work
Kindly add video implementation also for extension

**Comment by Atharv-110** [comment]
I will add video in comments only.

**Comment by harshita214** [comment]
@Atharv-110 ??

**Comment by Atharv-110** [comment]
https://user-images.githubusercontent.com/87393095/159849349-dea914ac-cd19-4bcf-8c3e-a6bf7d934356.mp4

@harshita214 here's the video and sorry for the delay.

**Comment by Atharv-110** [comment]
@harshita214 do i need to add this video in readme?

**Comment by Atharv-110** [comment]
Hey @harshita214, I have updated the Readme File with the Demo Video.

**Comment by Spring-dot** [comment]
@Atharv-110  Good work! 👍

**Pull request merged**
