### PR TITLE
Dark Theme Color Palette Generator

### PR DESCRIPTION
**Pull request by DarkFalc0n**
#82 

https://user-images.githubusercontent.com/59203815/155532674-406e1675-411a-4512-ba48-d63cfcbdac80.mp4

### CODE REVIEW

**Comment by harshita214** [comment]
Kindy add demo video in readme file also , rest is good

**Comment by harshita214** [comment]
Is this working only on specific browser?

**Comment by DarkFalc0n** [comment]
> Is this working only on specific browser?

It will work on all chromium based-browsers. I am using Brave here, but it should also work on Google Chrome and Chromium version of Edge

**Comment by harshita214** [comment]
Okay 
Merging the PR 🚀 
Thanks for contributing 💛

**Pull request merged**
