### PR TITLE
Holiday Extension added

### PR DESCRIPTION
**Pull request by shreya024**
### 👨‍💻 Changes proposed
I have added html,css,js,manifest,images and gif for Holiday Extension

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

National_holiday

### CODE REVIEW

**Comment by shreya024** [comment]
@whiteHatpro Kindly review

**Comment by whiteHatpro** [comment]
@shreya024 good work!!
thanks for contributing🚀🚀💛

**Comment by shreya024** [comment]
@whiteHatpro this issue was a level2

**Comment by gurjeetsinghvirdee** [comment]
> @whiteHatpro @harshita214  this issue was a level2.Kindly make it a level2 as I had to spend a lot of time searching for the right api and then implement.

@harshita214 kindly fix the labels

**Comment by whiteHatpro** [comment]
@gurjeetsinghvirdee done

**Pull request merged**
