### PR TITLE
Added Chrome Extension - Crypto Currency

### LINKED ISSUE #269: Crypto-Currency Statistics Chrome Extension
### Is your extension request related to a problem? Please describe.

- Chrome Extension required for updates on Crypto Currency
- Since Blockchain is gaining a lot of attention these days, this extension is highly required

### Describe the solution you'd like.

- Chrome Extension would be implemented to solve the issue

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the extension here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #269 

### 👨‍💻 Changes proposed
- Added Chrome Extension for Exchange Rates of Top Trending Crypto Coins

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !

**Comment by hariketsheth** [comment]
@whiteHatpro @harshita214  can you review this PR

**Review by harshita214 — CHANGES_REQUESTED** [review]
Kindly remove all extra files of other extensions

**Comment by hariketsheth** [comment]
Its because I have opened multiple PRs from same fork. 
I can only remove the files of extensions I don't want to be added 
- Which is the `Dictionary` one #268 

Else, other files would be added only once whenever you merge the PR into main branch

**Review by harshita214 — CHANGES_REQUESTED** [review]
@hariketsheth Make a readme file with description of extension and add picture , video of extension

**Comment by harshita214** [comment]
> Its because I have opened multiple PRs from same fork. I can only remove the files of extensions I don't want to be added
> 
> * Which is the `Dictionary` one [Chrome Extension Added - Dictionary #268](https://github.com/harshita214/Chrome-Extension/pull/268)
> 
> Else, other files would be added only once whenever you merge the PR into main branch

Yes you have to remove all the files except for this extension

**Comment by hariketsheth** [comment]
> > Its because I have opened multiple PRs from same fork. I can only remove the files of extensions I don't want to be added
> > 
> > * Which is the `Dictionary` one [Chrome Extension Added - Dictionary #268](https://github.com/harshita214/Chrome-Extension/pull/268)
> > 
> > Else, other files would be added only once whenever you merge the PR into main branch
> 
> Yes you have to remove all the files except for this extension

It can't be removed. 
I have opened PRs from same fork. So All the files would be visible at once. But if you merge, Files would be added only once

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !
@whiteHatpro @harshita214 can you review this PR

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !
@whiteHatpro @harshita214 can you review this PR

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !
@whiteHatpro @harshita214 can you review this PR

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !
@whiteHatpro @harshita214 can you review this PR

**Comment by hariketsheth** [comment]
@gurjeetsinghvirdee Please see to it !
Inactive From quite a few days. Since GSSoC Is going to end soon, request them to review it soon please !

**Comment by harshita214** [comment]
image

Kindly update readme file

**Comment by hariketsheth** [comment]
> image
> 
> Kindly update readme file

Done 👍🏻👍🏻
I have some more ideas for Extensions. Can I contribute still? 
I would expect that if you could review them a bit quick since some days left for GSSoC'22. If you permit I will open the respective issue and Open Pull Request soon

**Comment by harshita214** [comment]
> > image
> > Kindly update readme file
> 
> Done 👍🏻👍🏻 I have some more ideas for Extensions. Can I contribute still? I would expect that if you could review them a bit quick since some days left for GSSoC'22. If you permit I will open the respective issue and Open Pull Request soon

Great it looks fine to me
Thanks for contributing @hariketsheth 💛 

Yes, you can contribute more for sure!
Yes yes , I will keep that in mind :)

**Pull request merged**
