### PR TITLE
IT calculator

### PR DESCRIPTION
**Pull request by shouryap1**
This extension helps you in calculating income tax amount.
Screenshot from 2022-04-17 17-53-45
Screenshot from 2022-04-17 17-53-56

### CODE REVIEW

**Comment by harshita214** [comment]
Can you mention your issue?

**Comment by shouryap1** [comment]
Basically this it calculator helps you in calculating for take home salary + income tax amount. I created this chrome extension.

**Comment by shouryap1** [comment]
Can you please update?

**Comment by harshita214** [comment]
Issue No?

**Comment by shouryap1** [comment]
There was no issue in this as this is the first version created by me.

**Comment by whiteHatpro** [comment]
@shouryap1 add the ss and the video of the extension

**Review by shouryap1 — COMMENTED** [review]
This extension helps you in calculating income tax amount and take-home salary.
Screenshot from 2022-04-17 17-53-45
Screenshot from 2022-04-17 17-53-56

**Comment by shouryap1** [comment]
> @shouryap1 add the ss and the video of the extension

I have added screenshots for reference.

**Comment by shouryap1** [comment]
@harshita214 can you please update?

**Comment by whiteHatpro** [comment]
@shouryap1 thanks for contributing🚀🚀

**Pull request merged**
