### PR TITLE
Snake Chrome Extension

### PR DESCRIPTION
**Pull request by Krytax-24**
# Snake-Chrome-extension

Very basic chrome extension that let's you play snake with arrow keys (up, down, left, right) in a popup activated by clicking the extension icon.

Highscore gets saved in chrome.storage.sync, which means it's stored in the cloud (maintained between different chrome instances logged into same google account). 

Game is reset by closing and reopening the popup and no pause function is implemented (yet).

Written with Pure JavaScript, CSS and HTML snake
Game loop:
- check for collisions (wall, food, snake itself)
  - if collision with wall - end game
  - if collision with food - add new node, spawn new food
  - if collision with itself - end game
- advance snake (delete last node, add new)
- check if end of game (spawned enough food to end the game)

#Screenshots

screenshot 2

screenshot

#Video Demo

https://user-images.githubusercontent.com/81406458/159215333-ddb85e5f-3496-4d8a-a711-25c72c11101c.mp4

### CODE REVIEW

**Comment by harshita214** [comment]
@Krytax-24 good work
Just do one thing add pictures and video in readme file also

**Comment by Krytax-24** [comment]
> @Krytax-24 good work Just do one thing add pictures and video in readme file also

Done!

**Comment by harshita214** [comment]
Great, Merging the PR 🚀 
Thanks for Contributing 💙

**Comment by harshita214** [comment]
Kindly tell the issue number

**Comment by Krytax-24** [comment]
> Kindly tell the issue number

208

**Pull request merged**
