### PR TITLE
Chrome Extension Added - File Structure Github

### LINKED ISSUE #265: Github File Structure - Chrome Extension
### Is your extension request related to a problem? Please describe.

- Would like to add a Chrome Extension for Github
- This would show the File structure of the Github repositories
- It is very difficult in Github because every time user have to click and check the folder structure. User can't view the full File Structure all at once.

### Describe the solution you'd like.

I would like to implement a Chrome Extension for the same

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the extension here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #265 

### 👨‍💻 Changes proposed
- Files added for File Structure Chrome Extension
- Extension working successfully

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

@harshita214 Review this PR. 
Thank you !

### CODE REVIEW

**Comment by hariketsheth** [comment]
Since this add utility, I request you to give Level 3 label for this PR.

**Comment by harshita214** [comment]
Reviewing it
Kindly add an extension video also in the readme file

You can view another extension for an idea on how to make video, for example [this](https://github.com/harshita214/Chrome-Extension/tree/main/Dark%20ColorGen)

**Comment by hariketsheth** [comment]
> Reviewing it Kindly add an extension video also in the readme file
> 
> You can view another extension for an idea on how to make video, for example [this](https://github.com/harshita214/Chrome-Extension/tree/main/Dark%20ColorGen)

@harshita214 Proceed 👍🏻

**Comment by harshita214** [comment]
Great 👏 
Merging the PR 🚀 
Thanks for contributing 💙

**Comment by hariketsheth** [comment]
Since this adds Utility to Github 
@harshita214 Would it be possible to give Level 3 Label ?

**Comment by hariketsheth** [comment]
Since this adds Utility to Github
@harshita214 Would it be possible to give Level 3 Label ?

**Pull request merged**
