### PR TITLE
Chrome Extension Added - Dictionary

### LINKED ISSUE #267: Chrome Extension - Dictionary
### Is your extension request related to a problem? Please describe.

- Chrome Extension required for word search and meaning 
- A Dictionary would be implemented in Chrome Extension

### Describe the solution you'd like.

- Chrome Extension would be the solution

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the extension here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #267 

### 👨‍💻 Changes proposed
Added Chrome Extension for Dictionary

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

image

### CODE REVIEW

**Comment by hariketsheth** [comment]
Request you to add Level 2 and GSSoC Label for this !

**Comment by hariketsheth** [comment]
@whiteHatpro @harshita214  can you review this PR

**Comment by harshita214** [comment]
@hariketsheth kindly check #267

**Comment by hariketsheth** [comment]
Thanks not working on this Chrome Extension, then. Closing it

**Pull request closed without merging**
