### PR TITLE
ISSUE #167

### PR DESCRIPTION
**Pull request by whiteHatpro**

### CODE REVIEW

**Comment by seanw** [comment]
@whiteHatpro This code seems to be copied from a commercial Chrome extension that I own called https://www.checkbot.io/. Search for "checkbot.io" in https://github.com/harshita214/Chrome-Extension/pull/171 as evidence (e.g. https://raw.githubusercontent.com/whiteHatpro/Chrome-Extension/507d8c67b96806d7ffcfe22764f72edf5e842b97/seo%20checker/js/main.js) and compare the screenshots (including the Checkbot logo) shown on https://github.com/whiteHatpro/Chrome-Extension/tree/main/seo%20checker.

Please can you take down this fork and all public versions immediately? I did not give permission for this code to be distributed in this way.

(For info @harshita214)

**Comment by harshita214** [comment]
> @whiteHatpro This code seems to be copied from a commercial Chrome extension that I own called https://www.checkbot.io/. Search for "checkbot.io" in #171 as evidence (e.g. https://raw.githubusercontent.com/whiteHatpro/Chrome-Extension/507d8c67b96806d7ffcfe22764f72edf5e842b97/seo%20checker/js/main.js) and compare the screenshots (including the Checkbot logo) shown on https://github.com/whiteHatpro/Chrome-Extension/tree/main/seo%20checker.
> 
> Please can you take down this fork and all public versions immediately? I did not give permission for this code to be distributed in this way.
> 
> (For info @harshita214)

I understand @seanw your concern, we surely do not appreciate code plagiarism and using the code without permission. Thank you for bringing this issue to light, I will surely not accept this and merge it. Sorry for the inconvenience caused, I can assure you your code will not be used/merged without your permission.

**Comment by whiteHatpro** [comment]
@harshita214 really sorry for the mistake. I pushed the wrong directory into the GitHub... actually i was trying to make the clone of it but i guess the wrong file gor uploaded because of error in naming in the files
Really sorry for the inconvenience
@seanw really sorry sir and I myself respect the community and the efforts people put. Done unintentionally by mistake
Hope you understand!!!

**Comment by seanw** [comment]
@whiteHatpro Thanks for the quick response. Please can you remove all copies of any files taken or amended from my Checkbot extension that you've uploaded anywhere else public? e.g. I can still see https://github.com/whiteHatpro/Chrome-Extension/tree/main/seo%20checker and find it via GitHub search. You'll need to either delete the Git repo or use some approach to rollback the Git history to delete the commits entirely so they can no longer be viewed.

**Comment by whiteHatpro** [comment]
@seanw yess sir will do it by tonight!!
And really sorry for the convenience caused!!!

**Comment by seanw** [comment]
@whiteHatpro Thanks, please let me know when it's done.

**Comment by whiteHatpro** [comment]
@seanw I have removed the files!!
please confirm from your side

**Comment by seanw** [comment]
@whiteHatpro Thank you for the quick response. I'm happy now this has been resolved but please don't distribute these files again in the future, especially if they've been modified.

**Pull request closed without merging**
