### PR TITLE
music mode extension

### PR DESCRIPTION
**Pull request by mnnkhndlwl**
#53 

https://user-images.githubusercontent.com/75252077/153650480-2fb59bd8-7b2e-47fb-af42-6bd5a96cf6ee.mp4

### CODE REVIEW

**Comment by harshita214** [comment]
@mnnkhndlwl good, kindly add a readme file explaining the working of extension along with pictures/video of extension working, its features 
Also, this music extension will keep running right when the extension popup is closed?

**Comment by mnnkhndlwl** [comment]
yupp it would keep playing the tracks even if extension popup is closed

**Comment by mnnkhndlwl** [comment]
I have added the readme

**Comment by harshita214** [comment]
Great, Add the above video also

**Comment by mnnkhndlwl** [comment]
Done

**Pull request merged**
