### PR TITLE
RandomFact - Random Fact Generator

### PR DESCRIPTION
**Pull request by vaslal-324**
Issue #141 
# RandomFact : 
This is a Chrome Extension which generates a fact every time when clicked upon in the browser.
 
image

<br/><br/>
image

### CODE REVIEW

**Comment by vaslal-324** [comment]
Hey @harshita214 kindly review my PR

**Comment by harshita214** [comment]
Sure 👍

**Comment by harshita214** [comment]
@vaslal-324 you were trying to use [api](https://fungenerators.com/api/facts/) but you were facing some problem then did you solve it?
Since in code I can see you used an array of quotes

**Comment by vaslal-324** [comment]
> @vaslal-324 you were trying to use [api](https://fungenerators.com/api/facts/) but you were facing some problem then did you solve it? Since in code I can see you used an array of quotes

Yes, there wasn't proper API for that, hence I had to use an array

**Comment by harshita214** [comment]
Okay @vaslal-324 
Merging the PR 🚀 
Thanks for Contributing 💛

**Pull request merged**
