### PR TITLE
feat: timezone converter

### PR DESCRIPTION
**Pull request by r3yc0n1c**
solves issue #98 

---
Animation

### CODE REVIEW

**Review by harshita214 — CHANGES_REQUESTED** [review]
@r3yc0n1c your code and readme is not matching kindly look at them before creating a PR

**Comment by r3yc0n1c** [comment]
> @r3yc0n1c your code and readme is not matching kindly look at them before creating a PR

sorry for the inconvenience... just updated everything... can you review the PR and let me know if I need to change something?

**Comment by harshita214** [comment]
All good 👍 
Thanks for contributing, Merging the PR 🚀

**Review by harshita214 — COMMENTED** [review]
Done !

**Pull request merged**
