### PR TITLE
Chrome Extension Added - File Structure Github

### LINKED ISSUE #265: Github File Structure - Chrome Extension
### Is your extension request related to a problem? Please describe.

- Would like to add a Chrome Extension for Github
- This would show the File structure of the Github repositories
- It is very difficult in Github because every time user have to click and check the folder structure. User can't view the full File Structure all at once.

### Describe the solution you'd like.

I would like to implement a Chrome Extension for the same

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the extension here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #265 

### 👨‍💻 Changes proposed
- Files added for File Structure Chrome Extension
- - Extension working successfully
- 

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !

**Comment by hariketsheth** [comment]
@whiteHatpro @harshita214  can you review this PR

**Comment by hariketsheth** [comment]
@whiteHatpro @harshita214 can you review this PR

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !
@whiteHatpro @harshita214 can you review this PR

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !
@whiteHatpro @harshita214 can you review this PR

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !
@whiteHatpro @harshita214 can you review this PR

**Comment by hariketsheth** [comment]
@gurjeetsinghvirdee Please see to it !
Inactive From quite a few days. Since GSSoC Is going to end soon, request them to review it soon please !

**Comment by harshita214** [comment]
@hariketsheth kindly update readme file 

image

**Comment by hariketsheth** [comment]
> @hariketsheth kindly update readme file
> 
> image

Done 👍🏻👍🏻
Updated

**Comment by hariketsheth** [comment]
Since its adding utility to Github, by introducing a whole view of folder structure to a github repository. Would request you to give Level 3 Label for this one. If you feel the same !

**Comment by harshita214** [comment]
> > @hariketsheth kindly update readme file
> > image
> 
> Done 👍🏻👍🏻 Updated

Still  not updated

**Comment by hariketsheth** [comment]
image


I can't resolve the conflict from my side.
Hence, kindly check @harshita214 from your end

**Comment by gurjeetsinghvirdee** [comment]
> image
> 
> I can't resolve the conflict from my side. Hence, kindly check @harshita214 from your end

no one can resolve this conflict better to fetch your main or master branch
then use `git pull` after that push your changes

**Pull request closed without merging**
