### PR TITLE
Bug solved

### PR DESCRIPTION
**Pull request by iamrahulmahato**
issue no #218

### CODE REVIEW

**Comment by harshita214** [comment]
@Spring-dot kindly review this

**Comment by whiteHatpro** [comment]
@iamrahulmahato can u please show the working of the extension

**Comment by iamrahulmahato** [comment]
@whiteHatpro demo:

https://user-images.githubusercontent.com/49890655/163580182-6ffbc394-07b9-4572-8abb-024ca1e79ee0.mp4

**Comment by whiteHatpro** [comment]
@iamrahulmahato thanks for contributing🚀🚀

**Comment by iamrahulmahato** [comment]
@whiteHatpro haven't added any label?

**Comment by whiteHatpro** [comment]
@iamrahulmahato added the labels for you
and the issue is now being resolved
thanks

**Pull request merged**
