### PR TITLE
Sports News Tracker - Chrome Extension Added

### LINKED ISSUE #271: Chrome Extension - Sports News : Latest
### Is your extension request related to a problem? Please describe.

Extension required for Sport News

### Describe the solution you'd like.

A Chrome Extension required for Sport News (Latest)

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the extension here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #271 

### 👨‍💻 Changes proposed
Chrome Extension Added for News Tracking - Sports

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by hariketsheth** [comment]
Request you to add Level 2 and GSSoC Label for this !

**Comment by hariketsheth** [comment]
@whiteHatpro @harshita214  can you review this PR

**Review by harshita214 — CHANGES_REQUESTED** [review]
Delete files of other extensions from this PR
There are additional files in the PR of cryptocurrency, dictionary extension kindly remove all unnecessary files

**Review by harshita214 — CHANGES_REQUESTED** [review]
@hariketsheth Kindly add a video and picture of the extension in the readme file

**Pull request closed without merging**
