### PR TITLE
Url

### PR DESCRIPTION
**Pull request by mnnkhndlwl**
#63 

https://user-images.githubusercontent.com/75252077/153770082-d5d25273-1ea1-4106-8661-44fcead920d4.mp4

### CODE REVIEW

**Comment by harshita214** [comment]
@mnnkhndlwl good URL shortener is working pretty good, Can you add a button for Copy also to copy the generated URL

**Comment by mnnkhndlwl** [comment]
ok I try

**Comment by mnnkhndlwl** [comment]
@harshita214 I tried but it's not working it is giving this error 
searched on internet but it's not working
image

**Comment by mnnkhndlwl** [comment]
image
@harshita214 I have added copy button it's working fine
It was giving error initially I took me 2 hours to figure out why it's not working
I am commiting the changes

**Comment by mnnkhndlwl** [comment]
https://user-images.githubusercontent.com/75252077/153833555-7ed3c618-52ca-40d6-bf8e-4783f8b03f6b.mp4

**Comment by harshita214** [comment]
Awesome work 👏 @mnnkhndlwl, so good to see you figured it out and now it's working fine also.
Kindly update the readme file by adding the above video also.

**Comment by mnnkhndlwl** [comment]
@harshita214 one request can you assign hard label to this pr

**Comment by harshita214** [comment]
@mnnkhndlwl appreciable effort in PR 👏 , very good
Sorry can't change to a hard level, keep contributing 
Merging the PR as medium level
Thanks for contributing 💜

**Pull request merged**
