### PR TITLE
compound calculator

### PR DESCRIPTION
**Pull request by 03amir**
Compound Interest calculator

### CODE REVIEW

**Comment by harshita214** [comment]
@03amir I can see you made this for simple interest and not for compound interest,  correct it accordingly

**Comment by 03amir** [comment]
i think this will work . please check.

**Comment by harshita214** [comment]
Yes the code seems to work fine, do changes in readme file also

**Comment by 03amir** [comment]
Like what type of change?

**Comment by harshita214** [comment]
Kindly update the readme file, its a calculator
image
 Also, add a sample picture of the extension and then example pictures. Add the logo of extension also.

**Pull request merged**
