### PR TITLE
#149 weather ui, background change, color change, readme change

### PR DESCRIPTION
**Pull request by harshit0571**
ui changed of weather extension.

### CODE REVIEW

**Comment by harshit0571** [comment]
newdisplay1
newdisplay2
newdisplay3

added feature in which background changes with respect to the weather.
here are some screenshots!

**Review by harshita214 — COMMENTED** [review]
Kindly make folders of all background pictures used

**Comment by harshit0571** [comment]
ok i will do it

**Comment by harshita214** [comment]
@harshit0571 kindly do the changes

**Comment by harshit0571** [comment]
i am having problems in changing the branch.
i have sent a new pull request #181 please merge it.
sorry for inconvenience

**Comment by harshita214** [comment]
Okay @harshit0571

**Pull request closed without merging**
