### PR TITLE
Added File Converter Chrome Extension

### LINKED ISSUE #132: feat: JPG2PNG (JPG to PNG Converter) Chrome Extension
Hi, I'm a GSSOC'22 Contributor and I'd like to add a chrome extension wherein you can upload jpg file and get it converted to png file and download it.

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
# PR Description

- Added a Chrome extension using which you can convert JPG file to PNG file and vice versa

## Demo video

https://user-images.githubusercontent.com/80174214/159150830-08541cec-41e4-4ec1-a984-917a409a6f23.mp4

## Issue resolved

- Closes #132

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
Hi @harshita214 kindly review my PR

**Comment by harshita214** [comment]
@abhilipsasahoo03 kindly also add video implementation of extension

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 kindly also add video implementation of extension

Sure thing! I'll do it.

**Comment by abhilipsasahoo03** [comment]
Hi @harshita214 I've added a demo video in the README.md file as well as in the Pull Request Description body as per your request. Kindly look into it and let me know if any change is required.

**Comment by harshita214** [comment]
Good work!
Just one question there are two extra HTML and js files, why?
The code is using index2.html, index2.js

**Comment by abhilipsasahoo03** [comment]
> Good work!
> Just one question there are two extra HTML and js files, why?
> The code is using index2.html, index2.js 

Yeah I faced some errors implementing the JPG to PNG Converter and the PNG to JPG Converter in the same HTML file, so had to separate them and have them both linked to each other.

**Comment by harshita214** [comment]
> > Good work!
> > Just one question there are two extra HTML and js files, why?
> > The code is using index2.html, index2.js
> 
> Yeah I faced some errors while implementing the JPG to PNG Converter and the PNG to JPG Converter in the same HTML file, so had to separate them and have them both linked to each other. If there's any problem related to that, please let me know.

Okay okay, No problem
Awesome! Merging the PR 🚀 
Thanks for contributing 💙

**Pull request merged**
