### PR TITLE
Added gradient background

### PR DESCRIPTION
**Pull request by nickel-28**
I have modified the normal background to gradient background in CSS file of _Quotes Extension_

### CODE REVIEW

**Comment by harshita214** [comment]
In case of enhancement of UI kindly change the already presented pictures/video in the readme file

Kindly do this

**Comment by nickel-28** [comment]
> In case of enhancement of UI kindly change the already presented pictures/video in the readme file
> 
> Kindly do this

on which part I need to change?

**Comment by harshita214** [comment]
In readme file add ss and video

**Review by harshita214 — CHANGES_REQUESTED** [review]
In case of enhancement of UI kindly change the already presented pictures/video in the readme file

**Comment by harshita214** [comment]
@nickel-28 kindly do the changes

**Comment by Spring-dot** [comment]
@nickel-28 Have you made the changes? or working on it?

**Comment by nickel-28** [comment]
yeah done

**Pull request closed without merging**
