### PR TITLE
#114 Enhancing UI of BMI Calculator

### PR DESCRIPTION
**Pull request by IKRA786**
As a GSSOC'22 contributor, I enhance the UI of the BMI Calculator Chrome Extension.
Enhancement

### CODE REVIEW

**Comment by Spring-dot** [comment]
@IKRA786 Kindly add ss and video in the Readme file.

**Comment by IKRA786** [comment]
Updated ma'am please check once

**Comment by harshita214** [comment]
@IKRA786 you have to show video of extension not of HTML file, also can you enhance UI more changing its colors or the table colors

**Comment by harshita214** [comment]
@IKRA786 ??

**Comment by IKRA786** [comment]
Done mam changes please check

**Comment by harshita214** [comment]
@IKRA786 kindly add video implementation also
UI looks good 👍

**Comment by IKRA786** [comment]
Ma'am, I update Readme with video addition.

**Pull request merged**
