### PR TITLE
Birthday reminder extension

### LINKED ISSUE #231: Birthday extension
extension that counts down till your birthday and on your birthday 12 am plays happy birthday song (and maybe display colorful ribbons falling on your current open tab)

@harshita214

### PR DESCRIPTION
**Pull request by simplyNour**
### 🛠️ Fixes Issue

Closes #231 

### 🔧 Check List (Check the type of issue it fixes) 

- [ ] Bug Fix
- [x] New Extension
- [ ] Enhancement
- [ ] Documentation 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
demo

### CODE REVIEW

**Comment by harshita214** [comment]
@simplyNour  The ss are not visible and nor is the video kindly change it 
image

**Comment by simplyNour** [comment]
@harshita214 kindly check now

**Comment by whiteHatpro** [comment]
@simplyNour thanks for contributing🚀🚀

**Comment by harshita214** [comment]
@simplyNour Kindly update pictures
Its still not visible

**Pull request merged**
