### PR TITLE
Cricket Series Extension

### PR DESCRIPTION
**Pull request by shreya024**
I have added the Cricket Series Extension
Related Issue: #165 

cricket_series_extension

### CODE REVIEW

**Comment by shreya024** [comment]
@harshita214 @Spring-dot Kindly review my PR

**Comment by whiteHatpro** [comment]
@shreya024 nice work!!
thanks for contributing!!💛💛🚀

**Comment by shreya024** [comment]
> @shreya024 nice work!! thanks for contributing!!💛💛🚀
Thank you :)

**Comment by harshita214** [comment]
@shreya024 In the readme file images and video is not loading, kindly check it and do the changes accordingly

image

**Comment by shreya024** [comment]
> @shreya024 In the readme file images and video is not loading, kindly check it and do the changes accordingly
> 
> image

I believe there was some issue in merging as the images folder never got merged.So you can find it added along with my next PR
https://github.com/harshita214/Chrome-Extension/pull/201

**Comment by harshita214** [comment]
Okay @shreya024

**Comment by harshita214** [comment]
@shreya024 video is still not available
image
Kindly do that

**Comment by shreya024** [comment]
> @shreya024 video is still not available image Kindly do that

Should be resolved by https://github.com/harshita214/Chrome-Extension/pull/213

**Pull request merged**
